security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_dashboard_operationnel
            logout:
                path: app_logout
                target: app_login
                invalidate_session: true
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                httponly: true
                samesite: lax
            login_throttling:
                max_attempts: 5
                interval: '15 minutes'

    role_hierarchy:
        ROLE_EMETTEUR_TERRAIN: [ROLE_USER]
        ROLE_SECRETARIAT_GEI: [ROLE_USER]
        ROLE_PFT: [ROLE_EMETTEUR_TERRAIN]
        ROLE_SAHOLTY: [ROLE_PFT]
        ROLE_COMITE_AIT: [ROLE_USER]
        ROLE_SUPERADMIN: [ROLE_SAHOLTY, ROLE_SECRETARIAT_GEI, ROLE_COMITE_AIT, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/2fa, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/admin/activites, roles: ROLE_PFT }
        - { path: ^/admin/marches, roles: ROLE_PFT }
        - { path: ^/admin/automations, roles: ROLE_PFT }
        - { path: ^/admin/rules, roles: ROLE_PFT }
        - { path: ^/admin/user, roles: ROLE_PFT }
        - { path: ^/admin/listes-reference, roles: ROLE_PFT }
        - { path: ^/admin, roles: ROLE_SUPERADMIN }
        - { path: ^/audit, roles: ROLE_PFT }
        - { path: ^/carte, roles: ROLE_PFT }
        - { path: ^/wizard, roles: ROLE_USER }
        - { path: ^/kpi, roles: ROLE_COMITE_AIT }
        - { path: ^/urgence, roles: ROLE_PFT }
        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
